"""Build a repo wheel for the install / upgrade Docker smoke tests.

``pip wheel`` is the historical builder and is what CI has, but a uv-created
virtualenv — the project's documented way to set up a dev environment — ships no
``pip`` at all, so the interpreter running pytest often cannot execute it. Fall
back to ``uv build``, which produces the same artifact from the same
``pyproject.toml`` and is guaranteed to be present in exactly the environments
where ``pip`` is not. Both honour ``SETUPTOOLS_SCM_PRETEND_VERSION``, so the
caller can pin the version either way.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

BUILD_TIMEOUT_SECONDS = 600

# A gitignored build input, generated by CI before it runs these tests. Without it the
# build backend fails, so a fresh clone or worktree would report a hatchling traceback
# for a missing prerequisite step rather than a real defect.
MANIFEST_PATH = REPO_ROOT / "vibe" / "show_runtime_manifest.json"
PREPARE_MANIFEST_COMMAND = "python scripts/prepare_local_show_runtime_manifest.py"


def _has_pip() -> bool:
    result = subprocess.run(
        [sys.executable, "-c", "import pip"],
        capture_output=True,
        timeout=60,
    )
    return result.returncode == 0


def _build_command(output_dir: Path) -> list[str]:
    if _has_pip():
        return [sys.executable, "-m", "pip", "wheel", ".", "--no-deps", "--wheel-dir", str(output_dir)]
    uv_path = shutil.which("uv")
    if uv_path:
        return [uv_path, "build", "--wheel", "--out-dir", str(output_dir)]
    raise AssertionError("Building the test wheel needs either pip or uv on PATH")


def build_wheel(output_dir: Path, *, version: str | None = None) -> Path:
    """Build the repo's wheel into *output_dir* and return its path."""

    if not MANIFEST_PATH.exists():
        pytest.skip(f"{MANIFEST_PATH.name} is missing — run `{PREPARE_MANIFEST_COMMAND}` first")

    env = os.environ.copy()
    if version:
        env["SETUPTOOLS_SCM_PRETEND_VERSION"] = version

    result = subprocess.run(
        _build_command(output_dir),
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        timeout=BUILD_TIMEOUT_SECONDS,
    )
    assert result.returncode == 0, result.stdout + result.stderr

    if version:
        wheel_path = output_dir / f"avibe_os-{version}-py3-none-any.whl"
        assert wheel_path.exists(), f"Expected built wheel at {wheel_path}"
        return wheel_path

    wheels = sorted(output_dir.glob("avibe_os-*.whl"))
    assert wheels, "Expected a built wheel for install test"
    return wheels[-1]
