from __future__ import annotations

import json
import os
import tomllib
from dataclasses import dataclass
from pathlib import Path

from .errors import HarnessError
from .paths import ensure_owner_directory, ensure_regular_file_mode


@dataclass(frozen=True)
class GeneratedConfig:
    everos_toml: Path
    ome_toml: Path
    ingest_dir: Path


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def write_generated_config(*, everos_root: Path, timezone: str) -> GeneratedConfig:
    """Write only non-secret fixed configuration into the isolated provider root."""
    ensure_owner_directory(everos_root)
    ingest_dir = ensure_owner_directory(everos_root / ".poc-empty-ingest")
    everos_toml = everos_root / "everos.toml"
    ome_toml = everos_root / "ome.toml"
    everos_toml.write_text(
        "\n".join(
            (
                "# Generated by the Avibe EverOS POC harness. No credentials or endpoint URLs.",
                "[memory]",
                f"timezone = {_toml_string(timezone)}",
                "",
                "[api]",
                'host = "127.0.0.1"',
                "port = 8000",
                "",
                "[memorize]",
                'mode = "chat"',
                "",
                "[multimodal]",
                f"file_uri_allow_dirs = [{_toml_string(str(ingest_dir))}]",
                "",
            )
        ),
        encoding="utf-8",
    )
    ome_toml.write_text(
        "\n".join(
            (
                "# Generated by the Avibe EverOS POC harness.",
                "[strategies.reflect_episodes]",
                "enabled = false",
                "",
                "[strategies.extract_foresight]",
                "enabled = false",
                "",
            )
        ),
        encoding="utf-8",
    )
    for path in (everos_toml, ome_toml):
        os.chmod(path, 0o600)
        ensure_regular_file_mode(path)
    _validate_generated_config(everos_toml, ome_toml, timezone)
    return GeneratedConfig(everos_toml=everos_toml, ome_toml=ome_toml, ingest_dir=ingest_dir)


def _validate_generated_config(everos_toml: Path, ome_toml: Path, timezone: str) -> None:
    provider = tomllib.loads(everos_toml.read_text(encoding="utf-8"))
    ome = tomllib.loads(ome_toml.read_text(encoding="utf-8"))
    if provider.get("memorize", {}).get("mode") != "chat":
        raise HarnessError("generated_config_mode_invalid")
    if provider.get("memory", {}).get("timezone") != timezone:
        raise HarnessError("generated_config_timezone_invalid")
    strategies = ome.get("strategies", {})
    if strategies.get("reflect_episodes", {}).get("enabled") is not False:
        raise HarnessError("generated_config_reflection_enabled")
    if strategies.get("extract_foresight", {}).get("enabled") is not False:
        raise HarnessError("generated_config_foresight_enabled")
